const WIDTH = 1920;
const HEIGHT = 1080;
const DIALOGUE_BUTTON_WIDTH = 745;
const DIALOGUE_BUTTON_HEIGHT = 129;

export {
    WIDTH,
    HEIGHT,
    DIALOGUE_BUTTON_WIDTH,
    DIALOGUE_BUTTON_HEIGHT
}