const WIDTH = 1920;
const HEIGHT = 1080;
const DIALOGUE_BUTTON_WIDTH = 900;
const DIALOGUE_BUTTON_HEIGHT = 100;

export {
    WIDTH,
    HEIGHT,
    DIALOGUE_BUTTON_WIDTH,
    DIALOGUE_BUTTON_HEIGHT
}